apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cephdata
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/cephdata"
